name = "Seki"
author = "ProjectNautic"
version = "2026.07.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd2048022cac546af4e5c9d58d3804218466ef27cf8d781317a74e5cbf9172e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
