name = "Seki"
author = "ProjectNautic"
version = "2026.07.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66dc6e14aebe1e5ee25c9635fb363ae3d428161eb7e9a0511e0701cc3ddc3feb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
